import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const roadmapMdPath = path.join(root, 'docs', 'ROADMAP.md');
const roadmapTsPath = path.join(root, 'src', 'data', 'roadmap.ts');

const startMarker = '<!-- ROADMAP_DATA_START -->';
const endMarker = '<!-- ROADMAP_DATA_END -->';

function fail(message) {
  console.error(`[roadmap:sync] ${message}`);
  process.exit(1);
}

function extractRoadmapJson(markdown) {
  const start = markdown.indexOf(startMarker);
  const end = markdown.indexOf(endMarker);

  if (start === -1 || end === -1 || end <= start) {
    fail('Could not find roadmap data markers in docs/ROADMAP.md');
  }

  const block = markdown.slice(start + startMarker.length, end);
  const jsonFence = /```json\s*([\s\S]*?)\s*```/m;
  const match = block.match(jsonFence);

  if (!match?.[1]) {
    fail('Could not find a JSON code block between roadmap markers');
  }

  return match[1].trim();
}

function validateStories(stories) {
  const validStatus = new Set(['completed', 'in-progress', 'planned']);

  if (!Array.isArray(stories)) {
    fail('Roadmap data must be a JSON array');
  }

  stories.forEach((story, index) => {
    const label = `story at index ${index}`;

    if (!story || typeof story !== 'object') {
      fail(`${label} is not an object`);
    }

    for (const key of ['id', 'title', 'description', 'priority', 'status', 'phase']) {
      if (!(key in story)) {
        fail(`${label} is missing required field: ${key}`);
      }
    }

    if (typeof story.id !== 'string' || story.id.length === 0) {
      fail(`${label} has invalid id`);
    }

    if (typeof story.title !== 'string' || story.title.length === 0) {
      fail(`${label} has invalid title`);
    }

    if (typeof story.description !== 'string' || story.description.length === 0) {
      fail(`${label} has invalid description`);
    }

    if (typeof story.priority !== 'string' || story.priority.length === 0) {
      fail(`${label} has invalid priority`);
    }

    if (!validStatus.has(story.status)) {
      fail(`${label} has invalid status: ${story.status}`);
    }

    if (typeof story.phase !== 'number') {
      fail(`${label} has invalid phase (must be number)`);
    }

    if ('pr' in story && typeof story.pr !== 'number') {
      fail(`${label} has invalid pr (must be number when present)`);
    }
  });
}

function toTsLiteral(stories) {
  const lines = stories.map((story) => {
    const fields = [
      `    id: ${JSON.stringify(story.id)},`,
      `    title: ${JSON.stringify(story.title)},`,
      `    description: ${JSON.stringify(story.description)},`,
      `    priority: ${JSON.stringify(story.priority)},`,
      `    status: ${JSON.stringify(story.status)},`,
    ];

    if (typeof story.pr === 'number') {
      fields.push(`    pr: ${story.pr},`);
    }

    fields.push(`    phase: ${story.phase},`);

    return ['  {', ...fields, '  },'].join('\n');
  });

  return lines.join('\n');
}

const markdown = fs.readFileSync(roadmapMdPath, 'utf8');
const jsonText = extractRoadmapJson(markdown);

let stories;
try {
  stories = JSON.parse(jsonText);
} catch (error) {
  fail(`Invalid JSON in docs/ROADMAP.md: ${error.message}`);
}

validateStories(stories);

const content = `// This file is auto-generated by scripts/sync-roadmap.mjs\n// Source of truth: docs/ROADMAP.md\n\nexport type RoadmapStatus = 'completed' | 'in-progress' | 'planned';\n\nexport interface RoadmapStory {\n  id: string;\n  title: string;\n  description: string;\n  priority: string;\n  status: RoadmapStatus;\n  pr?: number;\n  phase: number;\n}\n\nexport const roadmapStories: RoadmapStory[] = [\n${toTsLiteral(stories)}\n];\n`;

fs.writeFileSync(roadmapTsPath, content, 'utf8');
console.log(`[roadmap:sync] Wrote ${path.relative(root, roadmapTsPath)}`);
